language: python
python:
  - "3.6"
#env:
#  global:
#    - PIPENV_VENV_IN_PROJECT=1
#    - PIPENV_IGNORE_VIRTUALENVS=1

# command to install dependencies
install:
  - 'pip install pipenv'
  - 'pipenv install'
# # command to run tests

script:
  - echo "Unit tests"

after_script:

  # start the web app
  - |
    python api.py &
    APP_PID=$!

  # download and install ngrok
  - curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip > ngrok.zip
  - unzip ngrok.zip
  - ./ngrok http 5000 > /dev/null &

  # sleep to allow ngrok to initialize
  - sleep 2

  # extract the ngrok url
  - NGROK_URL=$(curl -s localhost:4040/api/tunnels/command_line | jq --raw-output .public_url)

  # execute the API tests
  - |
    curl -s $TRIGGER_URL -d'{
      "environment": "'"$TRAVIS_BRANCH-$TRAVIS_JOB_NUMBER"'",
      "url": "'"$NGROK_URL"'",
      "wait": true
    }'

  - kill $APP_PID
