language: python
python:
  - "3.5"
  - "3.6"
#env:
#  global:
#    - PIPENV_VENV_IN_PROJECT=1
#    - PIPENV_IGNORE_VIRTUALENVS=1

# command to install dependencies
install:
  - 'pip install pipenv'
  - 'pipenv install'
# # command to run tests
#script: pytes test